### ISSUE TITLE
Offer to help rewrite "Dealing with shebangs" website page

### ISSUE THREAD

**Issue by sdondley** [gugod/www.perlbrew.pl#8]
Thanks for your work on Perlbrew.

I read the page ["Dealing with shebangs"](https://perlbrew.pl/Dealing-with-shebangs.html) several times now. I think I understand what it's saying but I'm not entirely clear.

I'd like to offer to rewrite the page to improve its clarity if someone can review it for technical accuracy. If there is interest, please let me know and I will submit my work for your consideration.

Thanks.

**Comment by gugod** [comment]
Sorry for not replying earlier. The content of perlbrew.pl website is compiled from the "Github Wiki" of App-perlbrew repository. The source of that page can be found here:

https://github.com/gugod/App-perlbrew/wiki/Dealing-with-shebangs

Should you still be interested in contributing to this, feel free to just updated that wiki page. Thank s in advance !
